spring.datasource.url=jdbc:postgresql://localhost:5432/tradehub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.locations=classpath:db/migration



jwt.secret=X6r3qbq6C8DYDICFO35o9A0gr5A2ExIAFT6SF2znmG1
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000